### ISSUE TITLE
How do I set the component that is displayed when the itemsList is empty?

### ISSUE THREAD

**Issue by HyggeBo7** [HussainTaj-W/flutter-package-selection_menu#1]
How do I set the component that is displayed when the itemsList is empty?

Can I add a adaptive height based on the itemsList data?

![image](https://user-images.githubusercontent.com/29586966/66896521-8ce94780-f027-11e9-9d65-13fe5f799234.png)

**Comment by HussainTaj-W** [comment]
### How do I set the component that is displayed when the itemsList is empty?

Currently, a component for this specific task does not exist. When **itemsList** is empty an empty ListView is shown when DialogComponentsConfiguration or DropdownComponentsConfiguration is used.

You can use the ListViewComponent to achieve the required effect.

```dart
Widget _listViewBuilder(ListViewComponentData data) {
  if (data.itemCount == 0) {
    return Center(
      child: Text("There is nothing here."),
    );
  }
  return ListView.builder(
    itemBuilder: data.itemBuilder,
    itemCount: data.itemCount,
    padding: EdgeInsets.zero,
  );
}
```
Complete example [here.](https://github.com/HussainTaj-W/flutter-package-selection_menu-example/tree/master/lib/example_for_issues/issue_1)
![An empty list example](https://user-images.githubusercontent.com/54102433/67096396-f4f57600-f16c-11e9-8b10-d5df7bbf7ae5.gif)

### Can I add an adaptive height based on the itemsList data?
Yes. 
```dart
Widget itemBuilder(
    BuildContext context, Rectangle rectangle, OnItemTapped onItemTapped) {
  return Container(
    height: rectangle.size,
    //...
  );
}
```
Complete example [here.](https://github.com/HussainTaj-W/flutter-package-selection_menu-example/tree/master/lib/example_for_issues/issue_1)
![A variable widget high list item example](https://user-images.githubusercontent.com/54102433/67096428-076faf80-f16d-11e9-8c58-39dde21e272d.gif)

**Comment by HyggeBo7** [comment]
Thank you
