### ISSUE TITLE
Update List at runtime

### ISSUE THREAD

**Issue by LeonColt** [HussainTaj-W/flutter-package-selection_menu#2]
How to update list at runtime?

**Comment by HussainTaj-W** [comment]
Thank you for opening this issue.

**selection_menu 0.9.0** has been published.

Read the changelog [here.](https://pub.dev/packages/selection_menu#-changelog-tab-)

You can find the example for changing list on runtime [here.](https://github.com/HussainTaj-W/flutter-package-selection_menu-example/tree/master/lib/1_basic_08_SelectionMenuController%20Updating%20List%20Dynamically)

**Comment by LeonColt** [comment]
Thank you very much for quick response.
issue resolved.
