### ISSUE TITLE
enable menu size adaptive height

### ISSUE THREAD

**Issue by brizaldi** [HussainTaj-W/flutter-package-selection_menu#3]
![image](https://user-images.githubusercontent.com/41714881/82286060-06cf1e00-99c7-11ea-9b34-5651d21a8016.png)

is there a way to set height of the menu so that it can change dynamically depending on the size of the list of items inside it?

**Comment by HussainTaj-W** [comment]
The default behavior of the DropDown style is to expand to available space. Perhaps I need to rethink this. 

Luckily, you can change any part of this widget without needing to edit the source.

In your case, you would like to override `ListViewComponent` and `MenuComponent`.

Please check out the complete usage example [here](https://github.com/HussainTaj-W/flutter-package-selection_menu-example/blob/master/lib/example_for_issues/issue_3/main.dart) _(Please copy the code from this file if needed)_.

# Code Highlights

```dart
Widget _listViewBuilder(ListViewComponentData data) {
  return ListView.builder(
    itemBuilder: data.itemBuilder,
    itemCount: data.itemCount,
    padding: EdgeInsets.zero,
    shrinkWrap: true, // This here will make the ListView wrap to content.
  );
}

Widget _menuComponentBuilder(MenuComponentData data) {
  return ClipRect(
    child: Column(
      mainAxisSize: MainAxisSize.min, // This will make the column wrap to content.
      children: [data.listView],
    ),
  );
}

SelectionMenu<Rectangle>(
  componentsConfiguration: DropdownComponentsConfiguration(
  listViewComponent: ListViewComponent(builder: _listViewBuilder),
  menuComponent: MenuComponent(builder: _menuComponentBuilder,
  ),
  // Other Properties...
);
```

![Dynamic Resizing Example](https://user-images.githubusercontent.com/54102433/82399634-09854e00-9a6f-11ea-8ac5-4df0ff5a3a0e.gif)

I'm glad to see people are still using my work. **Thank you**. 🌟

**Comment by HussainTaj-W** [comment]
I assume the issue was resolved, so I'm closing the issue.

Feel free to reopen the issue if the problem persists.

**Comment by brizaldi** [comment]
i did as you say, and its working now, sorry if this is a little bit out of topic, but how can i remove white padding around ListView?

![image](https://user-images.githubusercontent.com/41714881/83096716-9f088980-a0d0-11ea-834a-80a5fab2a3ac.png)

**Comment by HussainTaj-W** [comment]
I'll add such a feature in the next release (which might take some time.) 

Currently, there is a workaround for this. Use `AnimationComponent`. 
You can copy the actual [`DropdownAnimationComponent`](https://github.com/HussainTaj-W/flutter-package-selection_menu/blob/54f8ed641f379faeff618f19bbfe40dfc5ea86a5/lib/src/widget_configurers/configurations/dropdown/dropdown_components_configuration.dart#L100) and edit [this line of code.](https://github.com/HussainTaj-W/flutter-package-selection_menu/blob/54f8ed641f379faeff618f19bbfe40dfc5ea86a5/lib/src/widget_configurers/configurations/dropdown/dropdown_components_configuration.dart#L169)
