### ISSUE TITLE
Change selected item programmatically

### ISSUE THREAD

**Issue by brizaldi** [HussainTaj-W/flutter-package-selection_menu#4]
is there a way to do this?

**Comment by HussainTaj-W** [comment]
No. I was going to propose a workaround, but there is a bug with that approach. 

I think I shall add this as a feature in the next version as well (which may take time.)

**Comment by HussainTaj-W** [comment]
Added in version 1.0.0 b67606fdc25e282c15dec749a740bbea440060b4
