### ISSUE TITLE
selection_menu is not  null-safety

### ISSUE THREAD

**Issue by gustavobartho** [HussainTaj-W/flutter-package-selection_menu#7]
Is there any prediction or possibility that the package will become null safety ?

**Comment by HussainTaj-W** [comment]
I didn't realize this package was still being used by others. I honestly think I made a mess of a code two years ago. But still, I'm glad to see people are still trying it. 

Released [version 1.0.0 null safe](https://pub.dev/packages/selection_menu/versions/1.0.0)! 



Commit b67606fdc25e282c15dec749a740bbea440060b4
